<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by www.codechief.org</title>
</head>
<body>
  <form action="{{route('crud.destroy',1)}}" method="post">
      @csrf
  @method('DELETE')
      <input type="text" placeholder="enter here" value="76" readonly>
      <input type="submit" value="submit">
  </form>
</body>
</html>
